# Generated by Django 3.0.8 on 2020-07-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200713_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articles_url',
            field=models.CharField(default=1, max_length=100, verbose_name='url'),
            preserve_default=False,
        ),
    ]
