# Generated by Django 3.0.8 on 2020-07-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_articles_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articles_url',
            new_name='article_url',
        ),
    ]
