# Generated by Django 3.0.6 on 2020-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Duyuru Başlığı')),
                ('icerik', models.TextField(verbose_name='Duyuru içeriği')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('isPublished', models.BooleanField(default=True)),
                ('thisNew', models.BooleanField(default=True)),
            ],
        ),
    ]
