# Generated by Django 3.0.6 on 2020-05-19 23:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='icerik',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='isPublished',
            field=models.BooleanField(default=True, verbose_name='yayındamı'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='thisNew',
            field=models.BooleanField(default=True, verbose_name='yenimi'),
        ),
    ]
