# Generated by Django 3.0.6 on 2020-05-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200520_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='image',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
