# Generated by Django 3.0.6 on 2020-05-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200520_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duyuru',
            name='images',
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
