# Generated by Django 3.0.6 on 2020-05-20 20:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200520_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Duyuru Başlığı')),
                ('icerik', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
