# Generated by Django 3.0.6 on 2020-05-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutP',
        ),
    ]
