# Generated by Django 3.0.6 on 2020-05-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200520_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutp',
            name='baslik',
            field=models.CharField(max_length=100, verbose_name='hakkımızda s. başlığı'),
        ),
    ]
