# Generated by Django 3.0.8 on 2020-07-13 12:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200521_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='başlık')),
                ('icerik', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='başlık')),
                ('icerik', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutP',
        ),
        migrations.DeleteModel(
            name='Duyuru',
        ),
    ]
