# Generated by Django 3.0.6 on 2020-05-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200515_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='yonetmen',
            field=models.CharField(default=1, max_length=50, verbose_name='yönetmen'),
            preserve_default=False,
        ),
    ]
