# Generated by Django 3.0.6 on 2020-05-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thisNew',
            field=models.BooleanField(default=True),
        ),
    ]
