# Generated by Django 3.0.6 on 2020-05-19 23:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_thisnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Film Resmi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='isPublished',
            field=models.BooleanField(default=True, verbose_name='yayındamı'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thisNew',
            field=models.BooleanField(default=True, verbose_name='yenimi'),
        ),
    ]
