# Generated by Django 3.0.6 on 2020-05-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_date']},
        ),
    ]
