# Generated by Django 3.0.6 on 2020-05-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200521_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='yonetmen',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default=1, max_length=100, verbose_name='kategori'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
    ]
