# Generated by Django 3.0.6 on 2020-05-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20200523_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='kategori')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
    ]
