# Generated by Django 3.0.6 on 2020-05-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20200527_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieCategory',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default=1, max_length=100, verbose_name='kategori'),
            preserve_default=False,
        ),
    ]
